# Functions used for data analysis


#### Loading libraries####
library(dplyr)
library(tidyr)
library(GenomicRanges)
library(edgeR)
library(lmerTest)

####Defining functions####

#Calculating cfChIP enrichment for individual genes
#The function is inspired by frag_counts() available at:
#https://github.com/Baca-Lab/cfchip_manuscript/blob/main/scripts/common_functions.R
in_house_frag_counts = function(frag_files,
                                sample_names,
                                targets, # bed file or granges object with target region coordinates
                                normalize = 'total_frags',  # 'total_frags' or a granges object or bed file name with sites for normalization
                                verbose = TRUE) {  
    
    if(class(targets) == 'character' && grepl('rds$', targets)) {
        targets = readRDS(targets)
    }
    
    if(class(normalize) == 'character' && grepl('bed$', normalize)) {
        normalize = import(normalize)
    }
    
    target_names = targets$SYMBOL
    counts_mat = matrix(NA, length(targets), length(frag_files))
    rownames(counts_mat) = target_names
    colnames(counts_mat) = sample_names
    
    count = 0
    for (f in frag_files) {
        count = count + 1
        
        if(verbose) {
            message('processing sample ', count, ' of ', length(frag_files))
            message('reading in ', f)
        }
        
        frag = readRDS(f)
        # ensure frags have been reduced to 1 bp
        if(!(all(width(frag) == 1))) {
            frag = resize(frag, width = 1, fix = 'center')
        }
        
        if (class(normalize) == 'character' && normalize == 'total_frags') {
            norm_denominator = length(frag)
            counts_mat[, count] = countOverlaps(targets, frag) / norm_denominator * 1e6
        } 
        if(is.null(normalize)){
            counts_mat[, count] = countOverlaps(targets, frag)
        }
        else {
            norm_denominator = sum(countOverlaps(normalize, frag)) %>% suppressWarnings()
            counts_mat[, count] = countOverlaps(targets, frag) / norm_denominator * 1e6
        }    
        
    }
    dge <- DGEList(counts_mat)
    dge <- calcNormFactors(dge,method = "TMM")
    lcpm <- cpm(dge, log = TRUE,prior.count = 1)
    return(list(lcpm,dge))
}

#Correlating cfChIP enrichment with tumor fraction
#The function is inspired by test_CREs() available at:
#https://github.com/Baca-Lab/cfchip_manuscript/blob/main/scripts/CREs.R
test_CREs = function(counts, # normalized counts matrix generated by in_house_frag_counts()
                     meta, # metadatasheet with columns specifieid below
                     hold_out = NA, # study_name of samples to hold out, 
                     corr_qvalue_threshold = 0.05,
                     top_n_by_sig,
                     trim_top_quantile = 0, #when calculating CRE signal, remove this top quantile of CREs by signal
                     filter_enrichment = 10, # for training, only use samples wtih enrichment > this value in metadata
                     filter_fragments = 2e6, # for training, only use samples wtih fragments > this value in metadata
                     reset_low_ctDNA = FALSE # should ctDNA values < 0.03 be set to 0.03? This is done to reduce noise in the low ctDNA range for Spearman correlation
) {
    
    # make sure all the required columns are present in the metasheet
    stopifnot(c('study_name', 'sample', 'enrichment', 'ctDNA', 'fragments') %in% colnames(meta))
    
    if(reset_low_ctDNA) {
        meta$ctDNA[!is.na(meta$ctDNA) & meta$ctDNA < 0.03]  = 0.03
    }
    # if there are multiple samples for an individual, only train on the one with the most fragments
    tmp = meta %>% group_by(sample) %>% slice_max(order_by = fragments) %>% dplyr::select(sample)
    training = tmp$sample
    
    if (any(!is.na(hold_out))) {
        # if a holdout sample is specified, remove it and samples from the same individual
        stopifnot(hold_out %in% meta$study_name)
        this_sample <- meta %>% 
            filter(study_name %in% hold_out) %>% 
            dplyr::select(sample) %>% 
            unlist()
        training = setdiff(training, this_sample)
    }
    
    training = intersect(training, colnames(counts))
    training = training[training %in% meta$sample[!is.na(meta$ctDNA) &
                                                      (meta$antibody == 'MeDIP' | meta$enrichment > filter_enrichment) &
                                                      meta$fragments > filter_fragments]]
    
    # keep only the relevant samples
    counts_subset = counts[, colnames(counts) %in% training]
    ctDNA = meta$ctDNA[meta$sample %in% colnames(counts_subset)]
    
    # make sure the study names line up as expected between the counts matrix and ctDNA info from the metadata
    stopifnot(colnames(counts_subset) == meta$study_name[meta$study_name %in% colnames(counts_subset)])
    
    
    corr_results = apply(counts_subset, 1,
                         function(x) {
                             tmp = cor.test(x, ctDNA, method = 'spearman')
                             c(tmp$estimate, tmp$p.value, mean(x))
                         }) %>%
        suppressWarnings() %>% 
        t()
    r_names <- rownames(corr_results)
    corr_results <- corr_results %>% 
        as.data.frame()
    rownames(corr_results) <- NULL
    corr_results$SYMBOL <- r_names
    colnames(corr_results) = c('rho', 'p.value', 'mean_signal', 'SYMBOL')
    corr_results$q.value = p.adjust(corr_results$p.value, method = 'fdr')
    corr_results$significant = corr_results$q.value < corr_qvalue_threshold
    
    neg_CREs = corr_results %>% 
        subset(rho < 0) %>% 
        slice_min(n = top_n_by_sig, order_by =p.value, with_ties = FALSE) %>% 
        dplyr::select(SYMBOL) %>% 
        unlist() %>% 
        unname()
    
    pos_CREs = corr_results %>% 
        subset(rho > 0) %>% 
        slice_min(n = top_n_by_sig, order_by =p.value, with_ties = FALSE) %>% 
        dplyr::select(SYMBOL) %>% 
        unlist() %>% 
        unname()
    
    ret = list(neg_CREs, pos_CREs, corr_results)
    names(ret) = c('neg_CREs', 'pos_CREs', 'corr_results')
    
    #calculate signal for all samples
    # only consider CREs with signal < the specified cutoff
    pos_CRE_mat = counts[pos_CREs,]
    pos_CRE_mat_sum = rowSums(pos_CRE_mat)
    pos_cut = quantile(pos_CRE_mat_sum, probs = 1 - trim_top_quantile)
    pos_CRE_mat = pos_CRE_mat[pos_CRE_mat_sum < pos_cut,]
    
    neg_CRE_mat = counts[neg_CREs,]
    neg_CRE_mat_sum = rowSums(neg_CRE_mat)
    neg_cut = quantile(neg_CRE_mat_sum, probs = 1 - trim_top_quantile)
    neg_CRE_mat = neg_CRE_mat[neg_CRE_mat_sum < neg_cut,]
    
    toadd = data.frame(
        sample = colnames(counts),
        pos_CRE_signal = colSums(pos_CRE_mat),      
        neg_CRE_signal = colSums(neg_CRE_mat)
    )
    ret = c(ret, toadd)
    
    ret
}
#Calculating individual gene differences between BL and Tx
calc_diff <- function(counts, #Gene level cfChIP enrichment returned by in_house_frag_counts()
                      meta, #cfChIP metadata for each sample
                      ){
    library(tidyr)
    #Selecting lung cancer samples
    meta <- meta %>% 
        filter(study_name == "Lung cancer")
    c_meta <- meta %>% 
        group_by(patient) %>% 
        summarise(n = n())
    meta <- meta %>% 
        left_join(c_meta, by = "patient") %>% 
        filter(n == 2)
    counts_sele <- counts[,meta$sample]
    df <- as.data.frame(counts_sele)
    df$SYMBOL <- rownames(df)
    rownames(df) <- NULL
    meta_sele <- meta %>% 
        dplyr::select(sample,patient,patient_group,sample_type)
    #Calculating gene enrichment differences
    df <- df %>% 
        pivot_longer(-SYMBOL) %>% 
        dplyr::rename("sample" = "name") %>% 
        dplyr::rename("signal" = "value") %>% 
        left_join(meta_sele, by = "sample") %>% 
        arrange(SYMBOL,patient) %>% 
        group_by(SYMBOL,patient) %>% 
        summarise(delta_counts = signal[sample_type == "On-treatment"]-
                      signal[sample_type == "Baseline"],
                  .groups = "drop") %>% 
        pivot_wider(names_from = patient,
                    values_from = delta_counts)
    return(df)
}


gene_coverage_array <- function(files #Paths to files of the relative gene coverage
                                #created with cfChIP_pembro/R/scripts/MANE_coverage.R
                                ){
    mats <- list()
    for(i in 1:length(files)){
        print(i)
        df <- read.table(files[i]) #Reding the coverage file. 
        #First coulmn in the file is the position relative to TSS
        #All other columns, except the last, are the gene SYMBOLS and the values 
        #represent the coverage for that gene at the given position
        #The last variable ("sample") just contains the sample name
        df_form <- df %>% 
            dplyr::select(-c(pos,sample))
        mat_t <- apply(as.matrix(df_form),
                       MARGIN = 2, 
                       FUN = as.numeric)
        #Creating coverage matrix of position x gene 
        colnames(mat_t) <- colnames(df_form)
        rownames(mat_t) <- df$pos
        #Creating a list of the coverage matrices
        mats[[i]] <- mat_t
    }
    #Evaluating whether position x gene dimension are identical across samples
    stopifnot(length(unique(map_int(mats, nrow))) == 1)
    stopifnot(length(unique(map_int(mats, ncol))) == 1)
    #Defining variables for each dimension
    genes <- colnames(mats[[1]])
    positions <- as.numceric(rownames(mats[[1]]))
    indivs <- basename(files)
    indivs <- gsub("_H3K4me3_MANE_TSS_coverage.txt","",indivs)
    #Creating the array
    cov_arr <- abind::abind(mats,along = 3)
    #Defining dimension names
    dimnames(cov_arr) <- list(position = positions,
                              gene = genes,
                              individual = indivs)
    return(cov_arr)
}

interactions_model <- function(counts, #Gene level cfChIP enrichment returned by in_house_frag_counts()
                               meta, #cfChIP metadata for each sample
                               integrate_peak_info = F, #If TRUE genes with the 
                               #number of peaks > peak_cutoff are investigated
                               peak_info = NULL, #Annotated peaks across all samples
                               peak_cutoff= 1, #If integrate_peak_info = TRUE, only 
                               #genes with  number of peaks > peak_cutoff are investigated
                               er = NULL, #Enrichment ratio cutoff
                               lib_size = NULL #Number of cfChIP fragments cutoff
                               ){
    if(integrate_peak_info){
        #Selecting genes with > peak_cutoff peak calls
        if(is.null(peak_info)){
            stop("When integrate_peak_info = TRUE, then provide peak_info")
        }
        peaks <- peak_info %>% 
            filter(annotation == "Promoter (<=1kb)") %>% 
            dplyr::select(sample,SYMBOL) %>% 
            unique() %>% 
            group_by(SYMBOL) %>% 
            summarise(n = n()) %>% 
            arrange(desc(n))
        selected_genes <- peaks %>% 
            filter(n >= peak_cutoff) %>% 
            pull(SYMBOL)
    }
    else{
        selected_genes <- rownames(counts)
    }
    #Filtering samples
    meta <- meta %>% 
        filter(study_name == "Lung cancer") %>% 
        filter_samples(er = er,
                       lib_size = lib_size)
    c_meta <- meta %>% 
        group_by(patient) %>% 
        summarise(n = n())
    meta <- meta %>% 
        left_join(c_meta, by = "patient") %>% 
        filter(n == 2)
    #Selecting genes and samples
    counts_sele <- counts[selected_genes,meta$sample]
    counts_sele <- counts_sele[rowSums(counts_sele) > 0,]
    df <- as.data.frame(counts_sele)
    df$SYMBOL <- rownames(df)
    rownames(df) <- NULL
    meta_sele <- meta %>% 
        dplyr::select(sample,patient,patient_group,sample_type)
    #Formatting data
    df <- df %>% 
        pivot_longer(-SYMBOL) %>% 
        dplyr::rename("sample" = "name") %>% 
        dplyr::rename("signal" = "value") %>% 
        left_join(meta_sele, by = "sample") %>% 
        arrange(SYMBOL,patient)
    gois <- unique(df$SYMBOL)
    res_df <- data.frame(SYMBOL = c(),
                         p_val = c(),
                         cof = c(),
                         responder = c(),
                         non_responder = c())
    #Analyzing genes with a linear mixed-effect model 
    for(i in 1:length(gois)){
        if(i%%100 == 0){
            print(paste("Progress is",round(i/length(gois)*100,1),"%"))
        }
        goi <- gois[i]
        df_sele <- df %>% 
            filter(SYMBOL == goi)
        #Performing test
        mod_lmer <- lmer(signal ~ sample_type * patient_group + (1 | patient),
                         data = df_sele) %>% 
            suppressWarnings()
        #extracting results
        sum_lmer <- summary(mod_lmer)
        p_val <- sum_lmer$coefficients[4,5]
        cof <- fixef(mod_lmer)["sample_typeOn-treatment:patient_groupresponder"]
        #Formatting output
        ddf <- df_sele %>% 
            group_by(patient,patient_group) %>% 
            summarise(delta_counts = signal[sample_type == "On-treatment"]-
                          signal[sample_type == "Baseline"],
                      .groups = "drop") %>% 
            group_by(patient_group) %>% 
            summarise(m_dif = mean(delta_counts))
        res_ddf <- data.frame(SYMBOL = goi,
                              p_val = p_val,
                              cof = cof,
                              responder = ddf$m_dif[2],
                              non_responder = ddf$m_dif[1])
        if(!isSingular(mod_lmer, tol = 1e-4)){
            res_df <- rbind(res_df, res_ddf)
        }
    }
    qs <- p.adjust(res_df$p_val, method ="fdr")
    res_df$q_val <- qs
    res_df <- res_df %>% 
        arrange(p_val)
    rownames(res_df) <- NULL
    return(res_df)
}

#Group patients based on cfChIP enrichment
dichotomize_patients_enrichment <- function(counts, #Gene level cfChIP enrichment returned by in_house_frag_counts()
                                            meta, #cfChIP metadata for each sample
                                            SYMBOL, #Gene SYMBOL where the enrichment will separate patients
                                            samples, #samples which should be used for the analysis
                                            er = NULL, #Enrichment ratio cutoff
                                            lib_size = NULL #Number of cfChIP fragments cutoff
                                            ){
    #Filter samples
    meta <- meta %>% 
        dplyr::filter(study_name == "Lung cancer") %>% 
        dplyr::filter(sample %in% samples)
    meta <- filter_samples(meta = meta,
                           er = er,
                           lib_size = lib_size)
    #Select genes and samples
    counts_sele <- counts[SYMBOL,meta$sample]
    df <- as.data.frame(counts_sele)
    df$sample <- rownames(df)
    rownames(df) <- NULL
    colnames(df)[1] <- "signal"
    meta_sele <- meta %>% 
        dplyr::select(sample, patient)
    df <- df %>% 
        left_join(meta_sele, by = "sample")
    #Define median and group samples
    med_signal <- median(df$signal)
    df <- df %>% 
        mutate(divider = ifelse(signal >= med_signal,1,0))
    return(df)
}

#Group patients based on gene enrichment dynamics
dichotomize_patients_dynamics <- function(counts, #Gene level cfChIP enrichment returned by in_house_frag_counts()
                                          meta, #cfChIP metadata for each sample
                                          SYMBOL, #Gene SYMBOL where the enrichment will separate patients
                                          er = NULL, #Enrichment ratio cutoff
                                          lib_size = NULL #Number of cfChIP fragments cutoff
                                          ){
    #Filter samples
    meta <- meta %>% 
        filter_samples(er = er,
                       lib_size = lib_size) %>% 
        filter(study_name == "Lung cancer") 
    c_meta <- meta %>% 
        group_by(patient) %>% 
        summarise(n = n())
    meta <- meta %>% 
        left_join(c_meta, by = "patient") %>% 
        filter(n == 2)
    #Select genes and samples
    counts_sele <- counts[SYMBOL,meta$sample]
    df <- as.data.frame(counts_sele)
    df$sample <- rownames(df)
    rownames(df) <- NULL
    colnames(df)[1] <- "signal"
    meta_sele <- meta %>% 
        dplyr::select(sample, patient, sample_type)
    #Define whether enrichment increases or decreases
    df <- df %>% 
        left_join(meta_sele, by = "sample") %>% 
        group_by(patient) %>% 
        summarise(delta_counts = signal[sample_type == "On-treatment"]-
                      signal[sample_type == "Baseline"],
                  .groups = "drop") %>% 
        mutate(divider = ifelse(delta_counts >= 0,1,0))
    return(df)
}

#Cluster patients based on gene enrichment
clusters_enrichment <- function(counts, #Gene level cfChIP enrichment returned by in_house_frag_counts()
                                meta, #cfChIP metadata for each sample
                                genes, #Gene SYMBOLs where the enrichment will separate patients
                                samples, #samples which should be used for the analysis
                                er = NULL, #Enrichment ratio cutoff
                                lib_size = NULL #Number of cfChIP fragments cutoff
                                ){
    #Filtering samples
    meta <- meta %>% 
        filter_samples(er = er,
                       lib_size = lib_size) %>% 
        filter(study_name == "Lung cancer") %>% 
        filter(sample %in% samples)
    df <- counts[genes,meta$sample] %>% 
        t()
    #Performing PCA
    pca_res <- prcomp(x = df, 
                      scale = TRUE,
                      center = TRUE)
    #Selecting first three principal components
    df <- pca_res$x[,1:3]
    #Performing clustering
    set.seed(4)
    cluster_res <- kmeans(x = df, 
                          centers = 2,
                          algorithm = "Hartigan-Wong")
    #Exporting cluster results
    center_df <- as.data.frame(cluster_res$centers)
    cluster_list <- split(names(cluster_res$cluster),
                          paste0("Cluster: ",cluster_res$cluster))
    cluster_df <- stack(cluster_list) %>% 
        dplyr::rename("sample" = "values") %>% 
        dplyr::rename("cluster" = "ind") %>% 
        left_join(meta, by = "sample")
    cluster_list <- split(cluster_df$patient,
                          cluster_df$cluster)
    return(cluster_list)
}

#Cluster patients based on gene enrichment dynamics
clusters_dynamic <- function(diff_df, #Gene enrichment dynamics returned by calc_diff()
                             meta, #cfChIP metadata for each sample
                             genes, #Gene SYMBOLs where the enrichment will separate patients
                             er = NULL, #Enrichment ratio cutoff
                             lib_size = NULL #Number of cfChIP fragments cutoff
                             ){
    #Filtering samples
    meta <- meta %>% 
        filter_samples(er = er,
                       lib_size = lib_size) %>% 
        filter(study_name == "Lung cancer") 
    c_meta <- meta %>% 
        group_by(patient) %>% 
        summarise(n = n())
    meta <- meta %>% 
        left_join(c_meta, by = "patient") %>% 
        filter(n == 2)
    #Formatting data and selecting patients
    df <- diff_df %>% 
        pivot_longer(-SYMBOL) %>% 
        dplyr::rename("patient" = "name") %>% 
        dplyr::rename("diff_counts" = "value") %>% 
        filter(patient %in% meta$patient) %>% 
        filter(SYMBOL %in% genes) %>% 
        pivot_wider(names_from = patient,
                    values_from = diff_counts) %>% 
        as.data.frame()
    rownames(df) <- df$SYMBOL
    df <- df %>% 
        dplyr::select(-SYMBOL) %>% 
        t()
    set.seed(2)
    #Performing clustering
    cluster_res <- kmeans(x = df, 
                          centers = 2,
                          algorithm = "Hartigan-Wong")
    #Exporting cluster results
    center_df <- as.data.frame(cluster_res$centers)
    cluster_list <- split(names(cluster_res$cluster),
                          paste0("Cluster: ",cluster_res$cluster))
    
    return(cluster_list)
}

#Calculating gene expression percentiles for RUV-III and GTEx data
calc_individual_percentile <- function(expression #RUV-III or GTEx expression dataset
                                       ){
    for(i in 1:ncol(expression)){
        print(round(i/ncol(expression)*100,2))
        sele_mat <- expression[,i]
        ranks <- rank(sele_mat,
                      ties.method = "max")
        if(i == 1){
            df <- data.frame(SYMBOL = names(sele_mat),
                             rank = ranks)
            rownames(df) <- NULL
        }else{
            ddf <- data.frame(SYMBOL = names(sele_mat),
                              rank = ranks)
            rownames(ddf) <- NULL
            df <- df %>% 
                left_join(ddf, by = "SYMBOL")
        }
        colnames(df)[i+1] <- colnames(expression)[i]
    }
    return(df)
}